// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxceSS3VzZWiATBjDtGuw3pVvJn0k4pwA',
    appId: '1:591625208418:web:eeb98cfd2fd9a80324473b',
    messagingSenderId: '591625208418',
    projectId: 'event-explore',
    authDomain: 'event-explore.firebaseapp.com',
    storageBucket: 'event-explore.appspot.com',
    measurementId: 'G-HZE1D9PY2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1mfLG8umAI59NR7CtqPvmTLpasTV98is',
    appId: '1:591625208418:android:23a7ddb2a5bcf4ee24473b',
    messagingSenderId: '591625208418',
    projectId: 'event-explore',
    storageBucket: 'event-explore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfPu8Fo881SsOBILkYRVG5EmJ19F4qVuQ',
    appId: '1:591625208418:ios:04f6a08ad054df9124473b',
    messagingSenderId: '591625208418',
    projectId: 'event-explore',
    storageBucket: 'event-explore.appspot.com',
    iosClientId: '591625208418-9mlnlinipi9q60ubiooll334p21022ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventExplorer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfPu8Fo881SsOBILkYRVG5EmJ19F4qVuQ',
    appId: '1:591625208418:ios:04f6a08ad054df9124473b',
    messagingSenderId: '591625208418',
    projectId: 'event-explore',
    storageBucket: 'event-explore.appspot.com',
    iosClientId: '591625208418-9mlnlinipi9q60ubiooll334p21022ir.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventExplorer',
  );
}
